# Generated by Django 4.2.27 on 2025-12-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, choices=[('drama', 'Драма'), ('comedy', 'Комедия'), ('action', 'Боевик'), ('documentary', 'Документальный'), ('thriller', 'Триллер')], max_length=20),
        ),
    ]
